<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><LangVersion>latest</LangVersion></PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <Compile Remove="Standalone/**/*.cs" />
    <Reference Include="BepInEx"><HintPath>../../BepInEx/core/BepInEx.dll</HintPath></Reference>
    <Reference Include="Game"><HintPath>../../ULTRAKILL_Data/Managed/Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="../../ULTRAKILL_Data/Managed/UnityEngine*.dll" />
  </ItemGroup>
</Project>
